import test from "node:test";
import assert from "node:assert/strict";
import { createBvsChallenge, validateBvsChallenge } from "../../src/bvp/challenge.mjs";
import { authority, lifecycle, method, toyEd25519 } from "../helpers.mjs";
let seed = 1; const randomBytes = async (length) => Uint8Array.from({ length }, () => seed++ & 255);
const hash = `sha256:${"a".repeat(64)}`;
function intent() { return { schema: "https://e.test/schema", schemaHash: hash, credentialType: "License", disclosureMode: "public", purpose: "Issue public license", sourceProvider: "registry", sourceVerificationMethod: "record", evidenceProfile: "https://e.test/evidence", evidenceProfileHash: hash, adapterId: "registry", adapterVersion: "1.0.0", adapterProfile: "https://e.test/adapter", adapterProfileHash: hash, jurisdiction: "US-NY" }; }
test("challenge creation and validation bind BVS, holder, and intents", async () => { const bvs = authority(1), holder = authority(2), bvsMethod = method(bvs); const ports = { randomBytes, clock: () => "2026-07-20T12:00:00Z", ed25519: toyEd25519, lifecycleEvidence: lifecycle(bvs, bvsMethod) }; const challenge = await createBvsChallenge({ bvsAuthority: bvs, bvsMethod, holderAuthority: holder, intents: [intent()] }, ports); const result = await validateBvsChallenge(challenge, "2026-07-20T12:01:00Z", 0, ports); assert.equal(result.result, "valid"); assert.equal(result.identityVerified, false); });
test("challenge validation rejects altered disclosure and duplicate intent", async () => { const bvs = authority(3), holder = authority(4), bvsMethod = method(bvs); const ports = { randomBytes, clock: () => "2026-07-20T12:00:00Z", ed25519: toyEd25519, lifecycleEvidence: lifecycle(bvs, bvsMethod) }; const challenge = await createBvsChallenge({ bvsAuthority: bvs, bvsMethod, holderAuthority: holder, intents: [intent()] }, ports); challenge.intents[0].disclosureMode = "selective"; assert.rejects(() => validateBvsChallenge(challenge, "2026-07-20T12:01:00Z", 0, ports), /public/); });
