import { mkdir, writeFile } from "node:fs/promises";
import { deflateSync } from "node:zlib";
import { join } from "node:path";

const table = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1; table[n] = c >>> 0; }
function crc(bytes) { let c = 0xffffffff; for (const byte of bytes) c = table[(c ^ byte) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
function chunk(name, data) { const type = Buffer.from(name); const length = Buffer.alloc(4); length.writeUInt32BE(data.length); const checksum = Buffer.alloc(4); checksum.writeUInt32BE(crc(Buffer.concat([type, data]))); return Buffer.concat([length, type, data, checksum]); }
function png(size, maskable = false) { const rgba = Buffer.alloc((size * 4 + 1) * size); const inset = maskable ? .2 : .12; for (let y = 0; y < size; y++) { const row = y * (size * 4 + 1); for (let x = 0; x < size; x++) { const p = row + 1 + x * 4; const nx = x / size, ny = y / size; const h = nx > .31 && nx < .41 && ny > inset && ny < 1 - inset || nx > .59 && nx < .69 && ny > inset && ny < 1 - inset || nx >= .4 && nx <= .6 && ny > .45 && ny < .55; rgba[p] = h ? 128 : 7; rgba[p + 1] = h ? 224 : 20; rgba[p + 2] = h ? 184 : 17; rgba[p + 3] = 255; } } const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(size, 0); ihdr.writeUInt32BE(size, 4); ihdr[8] = 8; ihdr[9] = 6; return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]), chunk("IHDR", ihdr), chunk("IDAT", deflateSync(rgba)), chunk("IEND", Buffer.alloc(0))]); }
const directory = join("app", "public", "icons"); await mkdir(directory, { recursive: true }); await Promise.all([["icon-192.png", 192, false], ["icon-512.png", 512, false], ["maskable-512.png", 512, true]].map(([name, size, maskable]) => writeFile(join(directory, name), png(size, maskable))));
